/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as StudiKasusRouteImport } from './routes/studi-kasus'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KeunggulanRouteImport } from './routes/keunggulan'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as DaftarBabooRouteImport } from './routes/daftar-baboo'
import { Route as CaraKerjaRouteImport } from './routes/cara-kerja'
import { Route as BabooCivilRouteImport } from './routes/baboo-civil'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiKasusRoute = StudiKasusRouteImport.update({
  id: '/studi-kasus',
  path: '/studi-kasus',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KeunggulanRoute = KeunggulanRouteImport.update({
  id: '/keunggulan',
  path: '/keunggulan',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarBabooRoute = DaftarBabooRouteImport.update({
  id: '/daftar-baboo',
  path: '/daftar-baboo',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraKerjaRoute = CaraKerjaRouteImport.update({
  id: '/cara-kerja',
  path: '/cara-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const BabooCivilRoute = BabooCivilRouteImport.update({
  id: '/baboo-civil',
  path: '/baboo-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baboo-civil': typeof BabooCivilRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/daftar-baboo': typeof DaftarBabooRoute
  '/harga': typeof HargaRoute
  '/keunggulan': typeof KeunggulanRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/masuk': typeof MasukRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studi-kasus': typeof StudiKasusRoute
  '/tentang': typeof TentangRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baboo-civil': typeof BabooCivilRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/daftar-baboo': typeof DaftarBabooRoute
  '/harga': typeof HargaRoute
  '/keunggulan': typeof KeunggulanRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/masuk': typeof MasukRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studi-kasus': typeof StudiKasusRoute
  '/tentang': typeof TentangRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baboo-civil': typeof BabooCivilRoute
  '/cara-kerja': typeof CaraKerjaRoute
  '/daftar-baboo': typeof DaftarBabooRoute
  '/harga': typeof HargaRoute
  '/keunggulan': typeof KeunggulanRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/masuk': typeof MasukRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studi-kasus': typeof StudiKasusRoute
  '/tentang': typeof TentangRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baboo-civil'
    | '/cara-kerja'
    | '/daftar-baboo'
    | '/harga'
    | '/keunggulan'
    | '/kontak'
    | '/layanan'
    | '/masuk'
    | '/sitemap.xml'
    | '/studi-kasus'
    | '/tentang'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baboo-civil'
    | '/cara-kerja'
    | '/daftar-baboo'
    | '/harga'
    | '/keunggulan'
    | '/kontak'
    | '/layanan'
    | '/masuk'
    | '/sitemap.xml'
    | '/studi-kasus'
    | '/tentang'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/baboo-civil'
    | '/cara-kerja'
    | '/daftar-baboo'
    | '/harga'
    | '/keunggulan'
    | '/kontak'
    | '/layanan'
    | '/masuk'
    | '/sitemap.xml'
    | '/studi-kasus'
    | '/tentang'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BabooCivilRoute: typeof BabooCivilRoute
  CaraKerjaRoute: typeof CaraKerjaRoute
  DaftarBabooRoute: typeof DaftarBabooRoute
  HargaRoute: typeof HargaRoute
  KeunggulanRoute: typeof KeunggulanRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  MasukRoute: typeof MasukRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudiKasusRoute: typeof StudiKasusRoute
  TentangRoute: typeof TentangRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studi-kasus': {
      id: '/studi-kasus'
      path: '/studi-kasus'
      fullPath: '/studi-kasus'
      preLoaderRoute: typeof StudiKasusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keunggulan': {
      id: '/keunggulan'
      path: '/keunggulan'
      fullPath: '/keunggulan'
      preLoaderRoute: typeof KeunggulanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-baboo': {
      id: '/daftar-baboo'
      path: '/daftar-baboo'
      fullPath: '/daftar-baboo'
      preLoaderRoute: typeof DaftarBabooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-kerja': {
      id: '/cara-kerja'
      path: '/cara-kerja'
      fullPath: '/cara-kerja'
      preLoaderRoute: typeof CaraKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baboo-civil': {
      id: '/baboo-civil'
      path: '/baboo-civil'
      fullPath: '/baboo-civil'
      preLoaderRoute: typeof BabooCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BabooCivilRoute: BabooCivilRoute,
  CaraKerjaRoute: CaraKerjaRoute,
  DaftarBabooRoute: DaftarBabooRoute,
  HargaRoute: HargaRoute,
  KeunggulanRoute: KeunggulanRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  MasukRoute: MasukRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudiKasusRoute: StudiKasusRoute,
  TentangRoute: TentangRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
